on:
    merge_group:
        types: [checks_requested]

jobs:
    test:
        environment: test-env
        runs-on: ubuntu-latest
        steps:
            - run: echo $((${{secrets.TEST_SECRET_2}} + ${{secrets.TEST_SECRET_2}}))
